document.writeln("    <div class=\"logo\"><h1>DFLAG-NEU</h1></div>")
document.writeln("    		<nav id=\"nav\">")
document.writeln("    			<ul>")
document.writeln("    				<li><a href=\"../../index.html\">主页</a></li>")
document.writeln("   				<li><a href=\"../../publications.html\">论文专利</a></li>")
document.writeln("   				<li><a href=\"../../project.html\">科研项目</a></li>")
document.writeln("   				<li><a href=\"../../awards.html\">获奖信息</a></li>")
document.writeln("   				<li><a href=\"../../books.html\">学术专著与教材</a></li>")
document.writeln("   				<li><a href=\"../../member.html\">学生信息</a></li>")
document.writeln("   				<li><a href=\"../../recruit.html\">招生信息</a></li>")
document.writeln("    			</ul>")
document.writeln("    		</nav>")